---
title: "covid Notebook"
output: html_notebook
---

Notes about analyses of covid 19 data.

```{r}
# remotes::install_github("GuangchuangYu/nCov2019")
require(nCov2019)
require(dplyr)

x <- get_nCov2019()
y <- load_nCov2019()

library(DataExplorer)
plot_str(x)

#obtain top 20 country
d <- y['global'] #extract global data
#l1 <- which(d$country != 'China')
#d <- d[l1,] #exclude China
n <- d %>% filter(time == time(y)) %>%
 top_n(20, cum_confirm) %>%
 arrange(desc(cum_confirm))


#plot top 20

require(ggplot2)
require(ggrepel)

ggplot(filter(d, country %in% n$country, d$time > "2020-01-01"),
 aes(time, cum_confirm, color=country)) +
 geom_line() +
 geom_text_repel(aes(label=country),
 function(d) d[d$time == time(y),]) +
 theme_minimal(base_size=14) +
 theme(legend.position = "none")
 

```

Now let's look at a few countries in more details, to see whether their number of cases have moved from an exponential to a logistic.


```{r, fig.asp=5}

d <- y['global'] #extract global data
countries <- c("Japan","China","United States","Canada","Spain","Italy","France","Germany","Czechia","Norway","Australia","Argentina","Morocco","South Korea","El Salvador","Syria","Russia","Denmark","Singapore","Israel")

this.data <- d[which(d$country %in% countries & d$cum_confirm>100),]

lm(log(cum_confirm)~time*country, data=this.data)


ggplot(this.data,
 aes(time, cum_confirm)) +
 geom_line() + 
  geom_smooth(method = "lm", formula = (log(cum_confirm) ~ time*country), se=FALSE) +
  facet_wrap(~country, ncol=2, scales="free")




```


Italy in more details

```{r}
d <- y['global'] #extract global data
italydata <- d %>%
filter(d$country == "Italy" & d$cum_confirm>100) %>%
select(time,cum_confirm)



italydata$new_cases <- italydata$cum_confirm - lag(italydata$cum_confirm)
italydata$R <- italydata$new_cases / lag(italydata$new_cases)

plot(R~time, data=italydata, type='l')
abline(a=1,b=0, lty=2)

mean(italydata$R, na.rm = TRUE)

```


United States in more details

```{r}
d <- y['global'] #extract global data
usdata <- d %>%
filter(d$country == "United States" & d$cum_confirm>100) %>%
select(time,cum_confirm)


usdata$new_cases <- usdata$cum_confirm - lag(usdata$cum_confirm)
usdata$R <- usdata$new_cases / lag(usdata$new_cases)

plot(R~time, data=usdata, type='l')
abline(a=1,b=0, lty=2)

mean(usdata$R, na.rm = TRUE)

```

Canada in more details

```{r}
d <- y['global'] #extract global data
canadadata <- d %>%
filter(d$country == "Canada" & d$cum_confirm>100) %>%
select(time,cum_confirm)



canadadata$new_cases <- canadadata$cum_confirm - lag(canadadata$cum_confirm)
canadadata$R <- canadadata$new_cases / lag(canadadata$new_cases)

plot(R~time, data=canadadata, type='l')
abline(a=1,b=0, lty=2)

mean(canadadata$R, na.rm = TRUE)

```
